spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_ENV}
    username: ${DB_USER}
    password: ${DB_PASSWD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://my-auth-server.com
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_PASSWD}
            scope: ${GOOGLE_SCOPE}
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}

